test: 
	./scanner samples/pl0a.p
	./scanner samples/pl0b.p
	./scanner samples/pl0c.p
	./scanner samples/pl0d.p
	./scanner samples/pl1a.p
	./scanner samples/pl2a.p
	./scanner samples/pl2b.p
	./scanner samples/pl2c.p
	./scanner samples/pl3a.p
	./scanner samples/pl3b.p